export interface CustomerOrder {
	id: number,
	orderProducts: [],
	orderServices: [],
	paymentMethodId: number,
	paymentMethodName: string,
	customerId: 73,
	customerName: string,
	customerType: string,
	coupon: boolean,
	loyaltyCard: boolean,
	membershipCard: boolean,
	discount: number,
	totalDiscount: number,
	couponDiscount: number,
	loyalityCardDiscount: number,
	membershipCardDiscount: number,
	tax: number,
	loaylityCardNo: string,
	couponNo: string,
	membershipCardNo: string,
	grossAmount: number,
	netAmount: number,
	branchIdd: number,
	branchName: string,
}
