export interface CustomerUpdate {
	id: number,
	name: string,
	contactNo: string,
	email: string,
	image: string,
	address: string,
	cnic: string,
	countryId: number,
	countryName: string,
	stateId: number,
	stateName: string,
	cityId: number,
	cityName: string,
	areaId: number,
	areaName: string,
	branchId: number,
	branchName: string,
}
