export interface CustomerBill {
	id: number,
	orderId: number,
	branchId: number,
	branchName: string,
	customerId: number,
	customerName: string,
	coupon: boolean,
	loyaltyCard: boolean,
	membershipCard: boolean,
	orderProductBillDetails: [],
	orderServiceBillDetails: [],
	paymentMethodId: number,
	paymentMethodName: string,
	totalDiscount: number,
	discount: number,
	discountAmount: number,
	membershipDiscount: number,
	couponDiscount: number,
	loyaltyDiscount: number,
	rewardDiscount: number,
	grossAmount: number,
	totalBill: number,
	dueDate: Date,
	billDate: Date
	tax: number,
}
