export interface User {
	id: number,
	email: string,
	image:any,
	name: string,
	fullName: null,
	designationId: number,
	designationName: string,
	branchId: number,
	branchName: string,
	departmentId: number,
	departmentName: string,
	modifiedAt: Date,
	modifiedBy: number,
	createAt: Date,
	createBy: number,
	countryId: number,
	countryName: string,
	stateId: number,
	stateName: string,
	cityId: number,
	cityName: string,
	active:any,
	userTypeId:number,
	altEmail:any,
	description:any,
	aboutDesc:any,
	altContact:any,
	cnic:any,
	contact:any,
	address:any,
	password:any,
	areaId: number,
	list:any,
	areaName: string,
}
