export interface User {
	id: number,
	email: string,
	name: string,
	fullName: null,
	designationId: number,
	designationName: string,
	branchId: number,
	branchName: string,
	departmentId: number,
	departmentName: string,
	modifiedAt: Date,
	modifiedBy: number,
	createAt: Date,
	createBy: number,
	countryId: number,
	countryName: string,
	stateId: number,
	stateName: string,
	cityId: number,
	cityName: string,
	areaId: number,
	areaName: string,
}
